name: 'Deploy a Portainer stack'
description: 'Github Action to deploy a stack to a Portainer instance'
author: 'Findz'
branding:
  icon: 'cloud'
  color: 'blue'

inputs:
  portainer-host:
    required: true
    description: 'Portainer host, eg. https://myportainer.instance.com'
  portainer-api-key:
    description: 'The API key for the Portainer instance'
    required: true

  swarm-id:
    required: true
    description: 'ID of the Swarm to deploy to'
  endpoint-id:
    required: true
    description: 'ID of the Portainer node to deploy to'
    
  stack-name:
    required: true
    description: 'Name for the Portainer stack'
  stack-definition:
    required: true
    description: 'The path to the docker-compose stack stack definition file, eg. stack-definition.yml'
  template-variables:
    required: false
    description: 'If given, these variables will be replaced in docker-compose file by handlebars'

runs:
  using: 'node12'
  main: 'dist/index.js'
